# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{higml}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Higginbotham"]
  s.date = %q{2011-06-09}
  s.description = %q{Higml is a terse format for converting a static input hash to a dynamic output hash.}
  s.email = %q{daniel@flyingmachinestudios.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "examples/affiliations.higml",
    "examples/application.higml",
    "examples/articles.higml",
    "examples/contacts.higml",
    "examples/homes.higml",
    "examples/messages.higml",
    "examples/pages.higml",
    "examples/profiles.higml",
    "examples/searches.higml",
    "examples/simulate.higml",
    "higml.gemspec",
    "lib/higml.rb",
    "lib/higml/applier.rb",
    "lib/higml/config.rb",
    "lib/higml/node.rb",
    "lib/higml/parser.rb",
    "lib/higml/value.rb",
    "spec/fixtures/application.higml",
    "spec/fixtures/higml-config.yml",
    "spec/fixtures/search.higml",
    "spec/fixtures/selectors_with_groups.higml",
    "spec/fixtures/with_import.higml",
    "spec/higml_spec.rb",
    "spec/lib/higml/applier_spec.rb",
    "spec/lib/higml/config_spec.rb",
    "spec/lib/higml/parser_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/flyingmachine/higml}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Higml is a terse format for converting an input hash to an output hash.}
  s.test_files = [
    "spec/higml_spec.rb",
    "spec/lib/higml/applier_spec.rb",
    "spec/lib/higml/config_spec.rb",
    "spec/lib/higml/parser_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

